### ISSUE TITLE
JDK7 Collections.sort()方法报错分析 | 独ǒ无②'s blog

### ISSUE THREAD

**Issue by pvphero** [pvphero/pvphero.github.io#2]
http://localhost:4000/2016/12/06/JDK7-Collections-sort-%E6%96%B9%E6%B3%95%E6%8A%A5%E9%94%99%E5%88%86%E6%9E%90/

**Comment by pvphero** [comment]
test

**Comment by impvphero** [comment]
text haha

**Comment by pvphero** [comment]
test
